.TH "JS" "1" "July 2021" "v1.0.0" "JS Explorer Help"
.SH "NAME"
\fBJS\fR
.QP
.P
Find the method you need without digging through the docs!

.
.SH POSSIBLE COMMANDS
.P
\fBjsexplorer\fP
Runs the explorer tool, allows you to save the entry at the end (optional)
.P
\fBjsexplorer plain\fP
Runs the tool without asking to save at the end
.P
\fBjsexplorer \-p\fP
Same as above, aliased p for plain
.P
\fBlookup [string to look up]\fP
If you save an entry, you can run lookup and the string to find that entry and print it
.P
\fBclearlookup\fP
Clears all jsexplorer saved entries
.SH BUGS
.P
Please report any bugs to https://github\.com/sdras/js\-explorer/issues\.
.SH LICENSE
.P
Copyright (c) 2021, Sarah Drasner (MIT License)\.

